language: cpp

sudo: required
dist: trusty

matrix:
    include:
        - os: linux
          compiler: g++
          env: COMPILER=g++-5 CONFIG=Release
          addons:
              apt:
                  sources: ['ubuntu-toolchain-r-test']
                  packages: ['g++-5']

        - os: linux
          compiler: g++
          env: COMPILER=g++-5 CONFIG=Debug COVERAGE=on
          addons:
              apt:
                  sources: ['ubuntu-toolchain-r-test']
                  packages: ['g++-5']

        - os: linux
          compiler: clang++
          env: COMPILER=clang++-3.9 CONFIG=Release
          addons:
              apt:
                  sources:
                      - 'ubuntu-toolchain-r-test'
                      - sourceline: 'deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.9 main'
                        key_url: 'http://llvm.org/apt/llvm-snapshot.gpg.key'
                  packages: ['clang-3.9']

before_install:
    - chmod u+x travisAfterSuccess.sh travisScript.sh travisInstall.sh

install:
    - ./travisInstall.sh

script:
    - echo "Using compiler:"
    - ${COMPILER} -v
    - ./travisScript.sh

after_success:
    - ./travisAfterSuccess.sh

notifications:
    email: false
