language: cpp

os: linux
sudo: required
dist: trusty

matrix:
    include:
        - compiler: g++
          env: CONFIG=Release
        - compiler: g++
          env: CONFIG=Debug COVERAGE=on
        - compiler: clang++
          env: CONFIG=RELEASE

before_script:
    - chmod u+x travisAfterSuccess.sh travisScript.sh

script:
    - ./travisScript.sh

after_success:
    - ./travisAfterSuccess.sh

notifications:
    email: false
