language: cpp

compiler:
    - gcc
    - clang

os:
    -linux

sudo: required
dist: trusty

# Update versions of clang and cmake
before-install:
    - wget -nv -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
    - sudo apt-add-repository -y 'deb http://llvm.org/apt/trusty llvm-toolchain-trusty-3.9 main'
    - sudo apt-get update -qq
    - sudo apt-get install -qq -y clang-3.9
    - sudo apt-get install software-properties-common
    - sudo apt-add-repository -y 'ppa:george-edison55/cmake-3.x'
    - sudo apt-get update
    - sudo apt-get upgrade

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make test
