language: cpp

compiler:
    - gcc
    - clang

os:
    -linux

sudo: required
dist: trusty

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make test

notifications:
    email: false
