language: cpp

os: linux
sudo: required
dist: trusty

env:
    - COMPILER=g++-5 CONFIG=Release
    - COMPILER=g++-5 CONFIG=Debug COVERAGE=on
    - COMPILER=clang++-3.9 CONFIG=Release

before_install:
    - chmod u+x travisAfterSuccess.sh travisScript.sh travisInstall.sh travisInstallCompiler.sh
    - ./travisInstallCompiler.sh

install:
    - ./travisInstall.sh

script:
    - ./travisScript.sh

after_success:
    - ./travisAfterSuccess.sh

notifications:
    email: false
