language: cpp

os: linux
sudo: required
dist: trusty

compiler:
    - g++
    - clang++

env:
    - CONFIG=Release
    - CONFIG=Debug COVERAGE=on

matrix:
    exclude:
        - compiler: clang++
          env: CONFIG=Debug COVERAGE=on

install:
    - sudo apt-get install lcov

before_script:
    - chmod u+x travisAfterSuccess.sh travisScript.sh

script:
    - ./travisScript.sh

after_success:
    - ./travisAfterSuccess.sh

notifications:
    email: false
