language: cpp

os: linux
sudo: required
dist: trusty

compiler:
    - g++
    - clang++

env:
    - CONFIG=Release
    - CONFIG=Debug COVERAGE=on

matrix:
    exclude:
        - compiler: clang++
          env: CONFIG=Debug COVERAGE=on

before_install:
    - chmod u+x travisAfterSuccess.sh travisScript.sh travisInstall.sh

install:
    - bash -e ./travisInstall.sh

script:
    - bash -e ./travisScript.sh

after_success:
    - bash -e ./travisAfterSuccess.sh

notifications:
    email: false
